export const CATEGORIES = ["Semua Kategori", "MLB", "NY", "LA", "NBA"];

export const initialProducts = [
   {
      id: 1,
      name: "New Era 59FIFTY New York Yankees Basic Fitted",
      slug: "new-era-59fifty-ny-yankees-basic-fitted",
      price: 899000,
      stock: 18,
      category: 1,
      category_name: "NY",
      model: "59FIFTY Fitted",
      color: "Black / White",
      rating: 4.9,
      reviewsCount: 38,
      description: "Topi ikonik New Era 59FIFTY New York Yankees dalam warna hitam pekat dengan bordir 3D putih logo NY di bagian depan. Dilengkapi visor datar kokoh, crown terstruktur, dan stiker emas 59FIFTY visor resmi.",
      img: "/caps/cap_ny_black.jpg",
   },
   {
      id: 2,
      name: "New Era 9FORTY New York Yankees Heather Charcoal",
      slug: "new-era-9forty-ny-yankees-heather-charcoal",
      price: 649000,
      stock: 24,
      category: 1,
      category_name: "NY",
      model: "9FORTY Curved",
      color: "Heather Gray / Black",
      rating: 4.8,
      reviewsCount: 29,
      description: "Topi kasual New Era 9FORTY New York Yankees dengan siluet curved visor modern. Menggunakan bahan rajut katun heather gray premium dengan bordiran monogram NY kontras warna hitam dan strap pengatur di belakang.",
      img: "/caps/cap_ny_gray.jpg",
   },
   {
      id: 3,
      name: "New Era 59FIFTY LA Dodgers Matte Black",
      slug: "new-era-59fifty-la-dodgers-matte-black",
      price: 899000,
      stock: 14,
      category: 2,
      category_name: "LA",
      model: "59FIFTY Fitted",
      color: "Matte Black / White",
      rating: 4.9,
      reviewsCount: 45,
      description: "Topi fitted New Era 59FIFTY Los Angeles Dodgers edisi matte black. Menampilkan logo interlocking LA bersulam tebal di depan dan MLB batterman di belakang. Bahan 100% poliester performa tinggi anti-luntur.",
      img: "/caps/cap_la_black.jpg",
   },
   {
      id: 4,
      name: "New Era 9FIFTY Los Angeles Dodgers Two-Tone Charcoal",
      slug: "new-era-9fifty-la-dodgers-two-tone-charcoal",
      price: 749000,
      stock: 19,
      category: 2,
      category_name: "LA",
      model: "9FIFTY Snapback",
      color: "Charcoal Gray / Black",
      rating: 4.7,
      reviewsCount: 22,
      description: "Topi snapback New Era 9FIFTY LA Dodgers dengan perpaduan warna crown charcoal gray bertekstur wol dan visor hitam kontras. Dilengkapi kancing snapback yang mudah disesuaikan untuk kenyamanan harian.",
      img: "/caps/cap_la_gray.jpg",
   },
   {
      id: 5,
      name: "New Era 59FIFTY Chicago White Sox Classic Black",
      slug: "new-era-59fifty-chicago-white-sox-classic",
      price: 899000,
      stock: 12,
      category: 3,
      category_name: "MLB",
      model: "59FIFTY Fitted",
      color: "Jet Black / White",
      rating: 4.9,
      reviewsCount: 51,
      description: "Simbol streetwear legendaris! Topi New Era 59FIFTY Chicago White Sox dengan kaligrafi bordir klasik White Sox di depan. Pilihan favorit komunitas hip-hop dan skatestyle dunia.",
      img: "/caps/cap_mlb_sox.jpg",
   },
   {
      id: 6,
      name: "New Era 59FIFTY Boston Red Sox Graphite Edition",
      slug: "new-era-59fifty-boston-red-sox-graphite",
      price: 879000,
      stock: 15,
      category: 3,
      category_name: "MLB",
      model: "59FIFTY Fitted",
      color: "Graphite Gray / Navy",
      rating: 4.8,
      reviewsCount: 19,
      description: "Topi New Era 59FIFTY Boston Red Sox dalam balutan warna modern graphite gray dengan visor midnight navy. Logo huruf 'B' disulam dengan aksen outline merah-putih presisi tinggi.",
      img: "/caps/cap_mlb_redsox.jpg",
   },
   {
      id: 7,
      name: "New Era 9FIFTY Chicago Bulls Pro Black Snapback",
      slug: "new-era-9fifty-chicago-bulls-pro-black",
      price: 799000,
      stock: 20,
      category: 4,
      category_name: "NBA",
      model: "9FIFTY Snapback",
      color: "Black / Red Details",
      rating: 5.0,
      reviewsCount: 64,
      description: "Edisi resmi NBA Chicago Bulls dari New Era. Menampilkan bordiran kepala banteng ikonik Chicago Bulls di panel depan dengan logo NBA di bagian belakang. Wajib dimiliki penggemar basket dan fashion streetwear.",
      img: "/caps/cap_nba_bulls.jpg",
   },
   {
      id: 8,
      name: "New Era 9FIFTY Los Angeles Lakers All-Black Stealth",
      slug: "new-era-9fifty-la-lakers-all-black-stealth",
      price: 799000,
      stock: 16,
      category: 4,
      category_name: "NBA",
      model: "9FIFTY Snapback",
      color: "Monochrome Blackout",
      rating: 4.8,
      reviewsCount: 33,
      description: "Koleksi New Era 9FIFTY NBA Los Angeles Lakers versi All-Black Stealth. Didesain minimalis monokrom dengan bordiran logo Lakers tonal hitam matte pada kain twill hitam pekat.",
      img: "/caps/cap_nba_lakers.jpg",
   }
];

export const products = initialProducts;